version: '3'
services:
  truenas-backup-config:
    image: reeeeegis/truenas-backup-config
    container_name: truenas-backup-config
    environment:
      - API_KEY=1-GDePtgDAEDtqf2NE8svx34ijI4sRkJjNRXoV1cQEMqBeAqrWBvcBVeg4q2xuWP0I
      - SEC_SEED=true
      - BACKUPLOC=/mnt/truenas-backup
      - MAXNR_OF_FILES=10
      - SERVER_URL=https://truenas
      - SCHEDULED_TIME=01:00
    volumes:
      - truenas-backup:/mnt/truenas-backup
volumes:
  truenas-backup:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/truenas-backup